services:
  redis:
    image: redis:7.2.5-alpine3.20
    environment:
      REDIS_URL: redis://host.docker.internal:6379
    expose:
      - 6379:6379
    profiles:
      - product


  postgredb:
    image: postgres:16.3-alpine3.20
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    profiles:
      - product

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgredb
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}
      REDIS_URL: redis
    volumes:
      - ./my-uploads:/usr/blog/uploads
    profiles:
      - product

volumes:
  postgres-data:
  my-uploads:
