version: '3.8'
services:

  redis:
    image: redis
    expose:
      - 6379
    profiles:
      - product
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:3000'
    depends_on:
      - redis
      - mysqldb
    links:
      - redis
      - mysqldb
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://admin:letmein@mysqldb:3306/blog
      - REDIS_URL=redis
    volumes:
      - ./my-uploads:/usr/blog/uploads
    profiles:
      - product

  mysqldb:
    image: mysql:8.0
    ports:
      - '3306:3306'
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    volumes:
      - ./db-data:/var/lib/mysql
    profiles:
      - product
volumes:
  mysql-data:
  my-uploads:

